# Constants
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
RATIO = 5
SCREEN_WIDTH = WINDOW_WIDTH/RATIO
SCREEN_HEIGHT = WINDOW_HEIGHT/RATIO
HALF_SCREEN_WIDTH = SCREEN_WIDTH/2
HALF_SCREEN_HEIGHT = SCREEN_HEIGHT/2
FPS = 60

TOUCH_SIZE = 26
TOUCH_PADDING = 6